Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.define "node1" do |node1|
    node1.vm.hostname = 'node1'
    node1.vm.network "private_network", type: "dhcp"
    node1.vm.provision :shell, path: "bootstrap.sh"
  end
  config.vm.define "node2" do |node2|
    node2.vm.hostname = 'node2'
    node2.vm.network "private_network", type: "dhcp"
    node2.vm.provision :shell, path: "bootstrap.sh"
  end
  config.vm.define "node3" do |node3|
    node3.vm.hostname = 'node3'
    node3.vm.network "private_network", type: "dhcp"
    node3.vm.provision :shell, path: "bootstrap.sh"
  end
end
